version: "3.9"
services:
  sri4nodepostgresdbfortests:
    image: postgres:${SRI4NODE_TESTS_POSTGRES_VERSION:-11}
    container_name: sri4node_pg${SRI4NODE_TESTS_POSTGRES_VERSION:-11}_fortests
    # expose:
    #   - 5432
    ports:
      - 15432:5432
    volumes:
      - ../docker/postgres_initdb:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 1s
      timeout: 30s
      retries: 10
      start_period: 3s

  # generic version that uses env variable SRI4NODE_TESTS_NODE_VERSION
  sri4nodetests:
    depends_on:
      sri4nodepostgresdbfortests:
        condition: service_healthy
    image: node:${SRI4NODE_TESTS_NODE_VERSION:-16}
    container_name: sri4node${SRI4NODE_TESTS_NODE_VERSION:-16}pg${SRI4NODE_TESTS_POSTGRES_VERSION:-11}tests
    user: "root"
    working_dir: /home/node/sri4node
    volumes:
      - ../:/home/node/source_app
    tty: true
    command: > # > denotes a long string separated over multiple lines, escape $ with $$ !!!
      bash -c '
        echo "Current user: $$(whoami)" && pwd &&
        cp -r ../source_app/* . &&
        chown -R node:node . &&
        # ls &&
        # | tr "\r" "\n"
        su node -c '\''
          npmi() {
            [ "${SRI4NODE_TESTS_SKIP_NPM_INSTALL}" = "true" ] || {
              rm -rf node_modules docs dist* package-lock.json &&
              echo "==== start npm install (using node $$( node --version ) and npm $$( npm --version ))" &&
              npm install --foreground-scripts=true --log-level info
            }
          }
          echo "Current user: $$(whoami)" &&
          ( npmi || npmi || npmi || npmi ) &&
          npm run test:inside_docker
        '\''
      '
  ### OBSOLETE, use sri4nodetests instead
  # sri4node16tests:
  #   depends_on:
  #     sri4nodepostgresdbfortests:
  #       condition: service_healthy
  #   image: node:16
  #   container_name: sri4node16pg${SRI4NODE_TESTS_POSTGRES_VERSION:-11}tests
  #   user: "root"
  #   working_dir: /home/node/sri4node
  #   volumes:
  #     - ../:/home/node/source_app
  #   tty: true
  #   command: > # > denotes a long string separated over multiple lines, escape $ with $$ !!!
  #     bash -c '
  #       echo "Current user: $$(whoami)" && pwd &&
  #       cp -r ../source_app/* . &&
  #       chown -R node:node . &&
  #       # ls &&
  #       # | tr "\r" "\n"
  #       su node -c '\''
  #         npmi() {
  #           [ "${SRI4NODE_TESTS_SKIP_NPM_INSTALL}" = "true" ] || {
  #             rm -rf node_modules docs dist* package-lock.json &&
  #             echo "==== start npm install (using node $$( node --version ) and npm $$( npm --version ))" &&
  #             npm install --foreground-scripts=true --log-level info
  #           }
  #         }
  #         echo "Current user: $$(whoami)" &&
  #         ( npmi || npmi || npmi || npmi ) &&
  #         npm run test:inside_docker
  #       '\''
  #     '

  # sri4node18tests:
  #   image: node:18
  #   container_name: sri4node18tests
  #   user: "root"
  #   working_dir: /home/node/sri4node
  #   volumes:
  #     - ../:/home/node/source_app
  #   tty: true
  #   command: > # > denotes a long string separated over multiple lines, escape $ with $$ !!!
  #     bash -c '
  #       echo "Current user: $$(whoami)" && pwd &&
  #       cp -r ../source_app/* . &&
  #       chown -R node:node . &&
  #       # ls &&
  #       su node -c '\''
  #         npmi() {
  #           [ "${SRI4NODE_TESTS_SKIP_NPM_INSTALL}" = "true" ] || {
  #             rm -rf node_modules docs dist* package-lock.json &&
  #             echo "==== start npm install (using node $$( node --version ) and npm $$( npm --version ))" &&
  #             npm install --foreground-scripts=true --log-level info
  #           }
  #         }
  #         echo "Current user: $$(whoami)" &&
  #         rm -rf node_modules docs dist* package-lock.json &&
  #         ( npmi || npmi || npmi || npmi ) &&
  #         npm run test:inside_docker
  #       '\''
  #     '

  # sri4node20tests:
  #   image: node:20
  #   container_name: sri4node20tests
  #   user: "root"
  #   working_dir: /home/node/sri4node
  #   volumes:
  #     - ../:/home/node/source_app
  #   tty: true
  #   command: > # > denotes a long string separated over multiple lines, escape $ with $$ !!!
  #     bash -c '
  #       echo "Current user: $$(whoami)" && pwd &&
  #       cp -r ../source_app/* . &&
  #       chown -R node:node . &&
  #       # ls &&
  #       su node -c '\''
  #         npmi() {
  #           [ "${SRI4NODE_TESTS_SKIP_NPM_INSTALL}" = "true" ] || {
  #             rm -rf node_modules docs dist* package-lock.json &&
  #             echo "==== start npm install (using node $$( node --version ) and npm $$( npm --version ))" &&
  #             npm install --foreground-scripts=true --log-level info
  #           }
  #         }
  #         echo "Current user: $$(whoami)" &&
  #         rm -rf node_modules docs dist* package-lock.json &&
  #         ( npmi || npmi || npmi || npmi ) &&
  #         npm run test:inside_docker
  #       '\''
  #     '
