REVOKE ALL PRIVILEGES ON SCHEMA sri4node FROM sri4node;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA sri4node FROM sri4node;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA sri4node FROM sri4node;
DROP USER sri4node;

DROP SCHEMA IF EXISTS sri4node CASCADE;

DROP FUNCTION IF EXISTS exec(text);